apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-nvme-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: timeweb-ssd
  hostPath:
    path: /mnt/nvme
    type: DirectoryOrCreate
