apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: story-stream
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/risenfrost/mnt/data/postgres"
  storageClassName: standard
