apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config-map
  namespace: story-stream
data:
  SERVER_PORT: "8810"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_NAME: "story-stream"
  NODE_ENV: "deployment"

