apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: story-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tatarjesus/story-stream-backend:latest
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 8810
          envFrom:
            - configMapRef:
                name: backend-config-map
            - secretRef:
                name: backend-secret

