apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: story-stream
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8810
      targetPort: 8810
