apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: story-stream
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8810
  type: ClusterIP
