version: '3.8'

services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    platform: linux/amd64
    container_name: pgadmin
    restart: always
    ports:
      - "5445:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin_data:/var/lib/pgadmin

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    platform: linux/amd64
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data

  story-stream-frontend:
    image: ivanmonichev/story-stream-frontend:latest
    platform: linux/amd64
    container_name: story-stream-frontend
    restart: always
    ports:
      - "3000:8080"
    environment:
      VITE_API_SERVER: ${VITE_API_SERVER}

  caddy:
    image: caddy:2.9.1-alpine
    platform: linux/amd64
    container_name: caddy
    restart: always
    depends_on:
      - story-stream-frontend
    environment:
      TZ: ${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/caddy/conf:/etc/caddy
      - ./volumes/caddy/data:/data
