apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: story-stream
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
#    cert-manager.io/cluster-issuer: letsencrypt
spec:
#  tls:
#    - hosts:
#        - music-demo.ru
#        - api.music-demo.ru
#        - db.music-demo.ru
#      secretName: ingress-tls
  rules:
    - host: music-demo.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8080
    - host: api.music-demo.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8810
    - host: db.music-demo.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80

