phantom:
  address: "api.music-demo.ru:443"
  uris:
    - "/load/cpu"
  load_profile:
    load_type: rps
    schedule: const(1,30) line(1,100,2m) const(100,2m)
  ssl: true
console:
  enabled: true
telegraf:
  enabled: false
influx:
  enabled: false
rcheck:
  enabled: false
