apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
data:
  SERVER_PORT: "8810"
  JWT_ACCESS_EXPIRE: "7d"
  JWT_SECRET: "HJBci3h2f23vb72vf"
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "story-stream"
  DB_PASSWORD: "a892dd132f51320a68df31b444604bc1"
  DB_NAME: "postgres"
