apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:      # работает только для тестов и на single-node
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
