apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: story-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        fsGroup: 5050
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin" ]
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config-map
            - secretRef:
                name: pgadmin-secret
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
