apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: story-stream
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pgadmin"
