apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: story-stream
spec:
  ports:
    - port: 80
      targetPort: 5050
      nodePort: 30080
  selector:
    app: pgadmin
  type: ClusterIP
