apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: story-stream
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: pgadmin
