apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: portainer-data
              mountPath: /data
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-pvc
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata:
  name: portainer
spec:
  type: LoadBalancer
  selector:
    app: portainer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
