apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"
  persistentVolumeReclaimPolicy: Retain
