apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config-map
data:
  TZ: "Europe/Moscow"
  Caddyfile: |
    :80 {
        encode gzip

        handle_path /frontend/* {
            uri strip_prefix /frontend
            reverse_proxy story-stream-frontend:8080
        }

        handle_path /api/* {
            uri strip_prefix /api
            reverse_proxy story-stream-backend:8810
        }

        handle_path /portainer/* {
            uri strip_prefix /portainer
            reverse_proxy portainer:9000
        }

        handle_path /pgadmin/* {
            uri strip_prefix /pgadmin
            reverse_proxy pgadmin:80 {
                header_up Host {host}
                header_up X-Script-Name /pgadmin4
                header_up X-Scheme http
            }
        }

        header {
            X-Frame-Options "DENY"
            X-XSS-Protection "1; mode=block"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "no-referrer-when-downgrade"
            Permissions-Policy "geolocation=(), microphone=(), camera=()"
            Cache-Control "no-store"
        }

        log {
            output file /data/log/access.log {
                format json
            }
        }

        handle_errors {
            respond "Что-то пошло не так!" 500
        }
    }
