apiVersion: v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: story-stream
spec:
  acme:
    email: risen15@yandex.ru
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx-ingress
