apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-stream-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-stream-backend
  template:
    metadata:
      labels:
        app: story-stream-backend
    spec:
      containers:
        - name: backend
          image: tatarjesus/story-stream-backend:latest
          ports:
            - containerPort: 8810
          envFrom:
            - configMapRef:
                name: backend-env
            - secretRef:
                name: backend-secrets
