apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.9.1-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: caddy-env
          volumeMounts:
            - name: caddy-conf
              mountPath: /etc/caddy
            - name: caddy-data
              mountPath: /data
      volumes:
        - name: caddy-conf
          configMap:
            name: caddy-config
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-pvc
