apiVersion: v1
kind: Service
metadata:
  name: story-stream-backend
spec:
  selector:
    app: story-stream-backend
  ports:
    - protocol: TCP
      port: 8810
      targetPort: 8810
  type: ClusterIP
